// Code generated by lark suite oapi sdk gen
package mini

import (
	"lost_found/api"
	"lost_found/api/core/request"
	"lost_found/core"
	"lost_found/core/config"
)

type Service struct {
	conf    *config.Config
	Authens *AuthenService
}

func NewService(conf *config.Config) *Service {
	s := &Service{
		conf: conf,
	}
	s.Authens = newAuthenService(s)
	return s
}

type AuthenService struct {
	service *Service
}

func newAuthenService(service *Service) *AuthenService {
	return &AuthenService{
		service: service,
	}
}

type AuthenAccessTokenReqCall struct {
	ctx     *core.Context
	authens *AuthenService
	body    *AuthenAccessTokenReqBody
	optFns  []request.OptFn
}

func (rc *AuthenAccessTokenReqCall) Do() (*UserAccessTokenInfo, error) {
	var result = &UserAccessTokenInfo{}
	req := request.NewRequest("mina/v2/tokenLoginValidate", "POST",
		[]request.AccessTokenType{request.AccessTokenTypeApp}, rc.body, result, rc.optFns...)
	err := api.Send(rc.ctx, rc.authens.service.conf, req)
	return result, err
}

func (authens *AuthenService) AccessToken(ctx *core.Context, body *AuthenAccessTokenReqBody, optFns ...request.OptFn) *AuthenAccessTokenReqCall {
	return &AuthenAccessTokenReqCall{
		ctx:     ctx,
		authens: authens,
		body:    body,
		optFns:  optFns,
	}
}

type AuthenUserInfoReqCall struct {
	ctx     *core.Context
	authens *AuthenService
	optFns  []request.OptFn
}

func (authens *AuthenService) UserInfo(ctx *core.Context, optFns ...request.OptFn) *AuthenUserInfoReqCall {
	return &AuthenUserInfoReqCall{
		ctx:     ctx,
		authens: authens,
		optFns:  optFns,
	}
}
