// Code generated by lark suite oapi sdk gen
package mini

import (
	"lost_found/api/core/tools"
)

type Authen struct {
}

type UserAccessTokenInfo struct {
	Uid				string   `json:"uid,omitempty"`
	OpenId           string   `json:"open_id,omitempty"`
	UnionId          string   `json:"union_id,omitempty"`
	SessionKey      string   `json:"session_key,omitempty"`
	TenantKey        string   `json:"tenant_key,omitempty"`
	ForceSendFields  []string `json:"-"`
}


type AuthenAccessTokenReqBody struct {
	//GrantType       string   `json:"grant_type,omitempty"`
	Code            string   `json:"code,omitempty"`
	ForceSendFields []string `json:"-"`
}

func (s *AuthenAccessTokenReqBody) MarshalJSON() ([]byte, error) {
	type cp AuthenAccessTokenReqBody
	raw := cp(*s)
	return tools.MarshalJSON(raw, s.ForceSendFields)
}
